services:
    node:
        image: 'node:14'
        container_name: 'orion'
        restart: 'always'
        user: 'node'
        working_dir: '/home/node/app'
        environment:
            - NODE_ENV=development
        volumes:
            - ./:/home/node/app
        expose:
            - '3000'
        ports:
            - '3000:3000'
        command: 'npm run start:dev'

    db-postgres:
        image: 'postgres:14'
        container_name: 'orion-db'
        restart: 'always'
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - volume-db:/var/lib/postgresql/data
        expose:
            - '5432'
        ports:
            - '5432:5432'
        env_file:
            - .env

    pgadmin:
        image: 'dpage/pgadmin4:7.1'
        container_name: 'orion-pgadmin'
        restart: 'always'
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        volumes:
            - volume-pgadmin:/var/lib/pgadmin
        expose:
            - '80'
        ports:
            - '8080:80'
        env_file:
            - .env

volumes:
    volume-db:
    volume-pgadmin:
